### ISSUE TITLE
Assignment Maximum Late Penalty

### ISSUE THREAD

**Issue by yeqingxi** [dilevin/computer-graphics-csc418#5]
Hi, I just want a clarification of the late penalty for assignments. When is the latest time we can submit our assignment after its deadline? Right now on MarkUs it says the maximum late penalty is at Saturday 8 a.m., which is 8 hours after the deadline. If i submit an assignment after 8 a.m. will it just result in a mark of 0?

**Comment by GavinBarill** [comment]
Please ignore what MarkUs says. We had to fake a maximum late period because we weren't allowed to start until after the late period ended (which with our unusual grading policy, would be 9 days after submission, which doesn't help our turnaround time). You will be deducted marks based on the syllabus. Ignore the MarkUs max late period.

**Comment by GavinBarill** [comment]
*we weren't allowed to start **marking** until
